---
- name: Start logrotate
  service: name=logrotate state=started

- name: Restart logrotate
#  service: name=logrotate state=restarted
  shell: logrotate -vf /etc/logrotate.d/logrotate.config

- name: Restart apache
  service: name=apache2 state=restarted